version: '3.8'

services:
  db:
    image: postgres:14.9-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  api:
    image: cart-backend
    container_name: api
    depends_on:
      - db
    ports:
      - "8080:8080"
